### ISSUE TITLE
Not working and debug mode yields no messages

### ISSUE THREAD

**Issue by biggzlar** [SublimeLinter/SublimeLinter-pydocstyle#26]
I just installed this via package control. The procedure was as follows

1. Install SublimeLinter
2. `(env): pip install pydocstyle` to my custom environment
3. Install SublimeLinter-pydocstyle

- nothing works

4. Add the path to pydocstyle to the preferences:paths section "~/env//lib/python3.6/site-packages/pydocstyle"

- still nothing :(

"Debug" message:
No lint results.

**Comment by braver** [comment]
Er, that's not a debug message. Please enable debug mode, restart Sublime Text, lint a python file, show us the full contents of the console.

**Comment by kaste** [comment]
Well, adding it to the `paths` section is probably not what you want because that would be like a global install.  `~/env//lib/python3.6/site-packages/pydocstyle` is the path to the source code of `pydocstyle`. What you want is in `~/env/bin/...`.  There you find the 'executables'.  And the setting is http://www.sublimelinter.com/en/stable/linter_settings.html#executable  Probably `~/env/bin/pydocstyle` or `['~env/bin/python', '-m', 'pydocstyle']` should work.
